# Deployment da aplicação conversão de peso
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-conversao-peso
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-conversao-peso
  template:
    metadata:
      labels:
        app: app-conversao-peso
    spec:
      containers:
        - name: app-conversao-peso
          image: israeldoamaral/conversao-peso:v1
          ports:
            - containerPort: 80
---
# Service da aplicação conversao peso
apiVersion: v1
kind: Service
metadata:
  name: app-conversao-peso
spec:
  selector:
    app: app-conversao-peso
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  #type: NodePort
  type: LoadBalancer